# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fc308783e8c84527a9a0d16580cd77db9dc2ce5ff6faed93a5182f0555cc4762a420f72fcc40363f3c65be227e83a79e1bbc9e04075948f0f24bac65cac6415

test:
  secret_key_base: f8043c5223c0afea702f16a289c1f2c9bbdf1e7d441ef9c697ed0a6f0b2303666cda390efbd22d7e59f9bad01aff90da75bffc2c6ef898a02127d5285dd6d41c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
